
export const YEARS = Array.from({ length: 26 }, (_, i) => 2000 + i);

export const GP_NAMES = [
  "Abu Dhabi Grand Prix",
  "Argentine Grand Prix",
  "Australian Grand Prix",
  "Austrian Grand Prix",
  "Azerbaijan Grand Prix",
  "Bahrain Grand Prix",
  "Belgian Grand Prix",
  "Brazilian Grand Prix",
  "British Grand Prix",
  "Canadian Grand Prix",
  "Chinese Grand Prix",
  "Dutch Grand Prix",
  "Eifel Grand Prix",
  "Emilia Romagna Grand Prix",
  "European Grand Prix",
  "French Grand Prix",
  "German Grand Prix",
  "Hungarian Grand Prix",
  "Indian Grand Prix",
  "Italian Grand Prix",
  "Japanese Grand Prix",
  "Korean Grand Prix",
  "Las Vegas Grand Prix",
  "Luxembourg Grand Prix",
  "Malaysian Grand Prix",
  "Mexican Grand Prix",
  "Mexico City Grand Prix",
  "Miami Grand Prix",
  "Monaco Grand Prix",
  "Portuguese Grand Prix",
  "Qatar Grand Prix",
  "Russian Grand Prix",
  "Sakhir Grand Prix",
  "San Marino Grand Prix",
  "Saudi Arabian Grand Prix",
  "Singapore Grand Prix",
  "Spanish Grand Prix",
  "Styrian Grand Prix",
  "Turkish Grand Prix",
  "Tuscan Grand Prix",
  "United States Grand Prix",
  "Vietnam Grand Prix"
].sort();

export const FEEDBACK_LEGEND = [
  { color: 'bg-green-600', label: 'Correct year + correct race', emoji: '🟩' },
  { color: 'bg-blue-600', label: 'Correct race, wrong year', emoji: '🟦' },
  { color: 'bg-yellow-500', label: 'Correct race, year close (±1-2y)', emoji: '🟨' },
  { color: 'bg-purple-600', label: 'Correct race, year far (3+y)', emoji: '🟪' },
  { color: 'bg-red-600', label: 'Wrong race', emoji: '🟥' },
];
